sudo: required
dist: xenial
language: go
go_import_path: github.com/CanonicalLtd/UCWifiConnect
go:
  - 1.6
env:
  matrix:
    - TEST_SUITE="--static"
    - TEST_SUITE="--unit"
before_install:
  - go get github.com/godbus/dbus
  - go get github.com/gorilla/mux

install:
  - echo "Skip. Install is done by the test script."
script: sh -v ./run-checks $TEST_SUITE
