name: wifi-connect 
version: '0.8'
summary: Connect your device to external wifi over temp wifi AP
description: |
    A solution to enable your device to connect to ian external
    wifi AP using a temporary wifi AP the device puts up and then
    opening its web portal. Note that wifi-connect daemon assumes
    control of device network management and other management solutions
    should not be simultaneously used.

grade: devel
confinement: strict

apps:
  run: 
    command: server
    plugs: [network, network-control, network-bind, network-manager, control]
    aliases: [wifi-connect_server]
  netman:
    command: netman
    plugs: [network-manager, network-control]
    aliases: [wifi-connect_netman]
  wifi-ap:
    command: wifi-ap
    plugs: [control, network]
    aliases: [wifi-connect_wifi-ap]
  daemon:
    command: daemon
    daemon: simple
    plugs: [network-manager, control, network-bind]
  netplan:
    command: netplan
    plugs: [network-setup-control]
    aliases: [wifi-connect_netplan]

plugs:
  control:
    interface: content
    content: socket-directory
    target: $SNAP_COMMON/sockets
    default-provider: wifi-ap

parts:
  go:
    plugin: go
    source: . 
    go-importpath: github.com/CanonicalLtd/UCWifiConnect 
    build-packages:
      - git
  assets:
    plugin: dump
    source: .
    stage:
      - static

