name: wifi-connect 
version: '0.2'
summary: simple http server 
description: |
  simple test server.

grade: devel
confinement: strict

apps:
  run: 
    command: bin/server
    plugs: [network, network-control, network-bind, network-manager, control]
  connect:
    command: bin/ssids
    plugs: [network-manager]
  unixhttpc:
    command: bin/unixhttpc
    plugs: [control]
  wifi-ap:
    command: bin/wifi-ap
    plugs: [control, network]

plugs:
  control:
    interface: content
    content: socket-directory
    target: $SNAP_COMMON/sockets
    default-provider: wifi-ap

parts:
  unixhttpc:
    plugin: go
    source: unixhttpc-tool
  go:
    plugin: go
    source: src
    #go-importpath: github.com/CanonicalLtd/UCWifiConnect

