name: wifi-connect 
version: '0.5'
summary: simple http server 
description: |
  simple test server.

grade: devel
confinement: strict

apps:
  run: 
    command: server
    plugs: [network, network-control, network-bind, network-manager, control]
  netman:
    command: netman
    plugs: [network-manager, network-control]
  wifi-ap:
    command: wifi-ap
    plugs: [control, network]
  daemon:
    command: daemon
    daemon: simple
    plugs: [network-manager, control, network-bind]

plugs:
  control:
    interface: content
    content: socket-directory
    target: $SNAP_COMMON/sockets
    default-provider: wifi-ap

parts:
  go:
    plugin: go
    source: . 
    go-importpath: github.com/CanonicalLtd/UCWifiConnect 
  assets:
    plugin: dump
    source: .
    stage:
      - static

