name: wifi-connect 
version: '0.3'
summary: simple http server 
description: |
  simple test server.

grade: devel
confinement: strict

apps:
  run: 
    command: bin/server
    plugs: [network, network-control, network-bind, network-manager, control]
  netman:
    command: bin/netman
    plugs: [network-manager]
  wifi-ap:
    command: bin/wifi-ap
    plugs: [control, network]

plugs:
  control:
    interface: content
    content: socket-directory
    target: $SNAP_COMMON/sockets
    default-provider: wifi-ap

parts:
  go:
    plugin: go
    source: src
    go-importpath: github.com/CanonicalLtd/UCWifiConnect 

